language: java
dist: trusty
sudo: true
before_cache:
   - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
   - $HOME/.gradle/caches/
   - $HOME/.gradle/wrapper/
   - $HOME/.m2

jdk:
    - openjdk11

matrix:
  fast_finish: true
  include:
     - jdk: openjdk11


script:
    -  gradle all

before_install:
   - sudo apt-get update -qq 
   - sudo apt-get install gradle

install: true
